apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd-service
  name: httpd-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: httpd-deploy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  
    
status:
  loadBalancer: {}
