apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: phpfpm-deploy-hpa
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 30
        type: Utilization
    type: Resource
  minReplicas: {{ .Values.phpfpmDeployment.replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phpfpm-deploy
status:
  currentMetrics: null
  desiredReplicas: 0
