apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpfpm-deploy
  name: phpfpm-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas:  {{ .Values.phpfpmDeployment.replicas }}
  selector:
    matchLabels:
      app: phpfpm-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: phpfpm-deploy
    spec:
      containers:
      - image: "{{ .Values.phpfpmDeployment.repository }}:{{ .Values.phpfpmDeployment.tag }}"
        name: phpfpm
        ports:
         -  containerPort: 9000
        envFrom:
          - secretRef:
              name: app-secrets
        env:
          - name: ENVIRONMENT_NAME
            value: "{{ .Values.ENVIRONMENT_NAME }}"
          - name: APP_VERSION
            value: {{ .Values.APP_VERSION }}  
        resources: 
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "150m"  
      initContainers:
        - name:  init-database
          image: busybox:1.28
          command: [ 'sh', '-c', "until nslookup postgres-service; do echo 'Database still not accessible'; sleep 2; done;" ]     
status: {}
