cluster: "bookcatalog_qa_cluster"
namespace: "bookcatalog-uat"
region: "us-east-1"
httpdDeployment:
  replicas: 2
  repository: 835590170478.dkr.ecr.us-east-1.amazonaws.com/book-catalog/httpd
  tag: httpd-1.0.25
phpfpmDeployment:
  replicas: 2
  repository: 835590170478.dkr.ecr.us-east-1.amazonaws.com/book-catalog/php-fpm
  tag: phpfpm-1.0.25
ingress:
  path: "/uat"
  order: 20
ENVIRONMENT_NAME: "UAT"
APP_VERSION: 1.0.25
