include:
    - local: 'pipeline-template/deploy-template.yml'

variables: 
  PHPFPM_REGISTRY_NAME: "658548981999.dkr.ecr.us-east-1.amazonaws.com/book-catalog/php-fpm"
  HTTPD_REGISTRY_NAME: "658548981999.dkr.ecr.us-east-1.amazonaws.com/book-catalog/httpd"

stages:
  - build-and-push
  - deploy

#To ensure pipeline triggers only when changes to the main branch
workflow:
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
        when: always
      - when: never    

Bump-version:
    stage: build-and-push
    image: bash:latest
    script: 
        - VERSION=$(cat VERSION)
        - IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        - PATCH=$((PATCH + 1))
        - NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        - echo "current version:- $VERSION"
        - echo "New version:- $NEW_VERSION"
        - echo "NEW_VERSION=$NEW_VERSION" >> build.env
    artifacts:
        reports:
          dotenv: build.env

Build-and-push:
    stage: build-and-push
    image: docker:27-cli

    services:
      - name: docker:27-dind

    variables:
      DOKCER_TLS_CERTDIR: ""

    needs:
      - job: Bump-version  
        artifacts: true

    before_script:
        - echo "Installing openssl utility..."
        - apk add --no-cache openssl  
        - echo "Installing AWS"
        - apk add --no-cache aws-cli
        - aws --version
        - env | grep -i "docker"

    script:
        - docker info
        #httpd image need ssl certs for enabling https the following command will generate the ssl cert and key
        - echo "Generating TLS certificate for httpd..."
        - mkdir -p httpd/ssl  
        - openssl req -x509 -nodes -days 1 -newkey rsa:2048 -keyout httpd/ssl/server.key -out httpd/ssl/server.crt -subj "/CN=localhost"

        - echo "building the docker image for httpd..."
        - docker build -t httpdimage -f httpd/httpdDockerfile .

        - echo "building the docker image for phpfpm..."
        - docker build -t phpfpmimage -f app/phpfpmDockerfile app/


        - echo "tagging images..."
        - docker tag docker.io/httpdimage "$HTTPD_REGISTRY_NAME:httpd-$NEW_VERSION"
        - docker tag docker.io/phpfpmimage "$PHPFPM_REGISTRY_NAME:phpfpm-$NEW_VERSION"

        - echo "Running ecr login"
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 658548981999.dkr.ecr.us-east-1.amazonaws.com

        - echo "pushing httpd image to ECR"
        - docker push "$HTTPD_REGISTRY_NAME:httpd-$NEW_VERSION"
        - echo "pushing phpfpm image to ECR"
        - docker push "$PHPFPM_REGISTRY_NAME:phpfpm-$NEW_VERSION"

        - echo "HTTPD_TAG=httpd-$NEW_VERSION" >> build.env
        - echo "PHPFPM_TAG=phpfpm-$NEW_VERSION" >> build.env

    artifacts:
      reports:
        dotenv: build.env    


Update-version:
  stage: build-and-push
  image: bash:latest
  needs:  
    - job: Bump-version
      artifacts: true
    - job: Build-and-push
  before_script: 
    - echo "install git"
    - apk update && apk add --no-cache git       
  script:
    - git config --global user.email "gitlab-ci@example.com"
    - git config --global user.name "GitLab CI Bot"
    - git remote set-url origin "https://oauth2:${GITLAB_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - echo "updating new image tag to  "
    - echo "updating new version back to VERSION file in the repo"
    - bash ./scripts/update-version.sh "$NEW_VERSION" VERSION

Deploy-QA:
  stage: deploy
  extends: .deploy_template
  variables:
    ENV: "qa"
  when: manual  

Deploy-uat:
  stage: deploy
  extends: .deploy_template
  variables:
    ENV: "uat"
  when: manual   

     


     