
stages:
  - build-and-push
  - beploy

#To ensure pipeline triggers only when changes to the main branch
workflow:
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
        when: always
      - when: never    

Bump-version:
    stage: build-and-push
    image: bash:latest
    script: 
        - VERSION=$(cat VERSION)
        - IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        - PATCH=$((PATCH + 1))
        - NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        - echo "current version:- $VERSION"
        - echo "New version:- $NEW_VERSION"
        - echo "NEW_VERSION=$NEW_VERSION" >> build.env
    artifacts:
        reports:
          dotenv: build.env

Build-and-push:
    stage: build-and-push
    image: docker:27-cli
    services:
      - docker:27-dind

    needs:
      - job: Bump-version  
        artifacts: true

    variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""  

    script:
        - echo "Logging in to GItab contianer registry"
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        #httpd image need ssl certs for enabling https the following command will generate the ssl cert and key
        - echo "Installing openssl utility..."
        - apk add --no-cache openssl
        - echo "Generating TLS certificate for httpd..."
        - mkdir -p httpd/ssl  
        - openssl req -x509 -nodes -days 1 -newkey rsa:2048 -keyout httpd/ssl/server.key -out httpd/ssl/server.crt -subj "/CN=localhost"

        - echo "building the docker image..."
        - docker compose build 

        - echo "listing docker images"
        - docker compose config --images

        - echo "tagging images..."
        - docker tag docker.io/php-postgres-bookapp/httpd:latest "$CI_REGISTRY_IMAGE:$NEW_VERSION"
        - docker tag docker.io/php-postgres-bookapp/phfpm:latest "$CI_REGISTRY_IMAGE:$NEW_VERSION"

        - echo "pushing image to gitlab registry"
        - docker push "$CI_REGISTRY_IMAGE:$NEW_VERSION"
        - docker push "$CI_REGISTRY_IMAGE:$NEW_VERSION"

        - echo "updating the version file"
        - echo "$NEW_VERSION" > VERSION
