cluster: "bookcatalog_qa_cluster"
namespace: "bookcatalog-qa"
region: "us-east-1"
httpdDeployment:
  replicas: 2
  repository: 835590170478.dkr.ecr.us-east-1.amazonaws.com/book-catalog/httpd
  tag: httpd-1.0.15
phpfpmDeployment:
  replicas: 2
  repository: 835590170478.dkr.ecr.us-east-1.amazonaws.com/book-catalog/php-fpm
  tag: phpfpm-1.0.15
ingress:
  path: "/qa/*"
  order: 10
ENVIRONMENT_NAME: "QA"
APP_VERSION: qa
