cluster: "bookcatalog_qa_cluster"
namespace: "bookcatalog-qa"
region: "us-east-1"
httpdDeployment:
  replicas: 2
  repository: vishnusatheesan/bookcataloghttpd
  tag: 0.0.2 

phpfpmDeployment:
  replicas: 2
  repository: vishnusatheesan/bookcatalogphpfpm
  tag:  0.0.1

