DocumentRoot "/var/www/html" 

DirectoryIndex index.php index.html

<Directory "/var/www/html"> 
    AllowOverride All
    Require all granted
</Directory>

<FilesMatch \.php$>
	SetHandler "proxy:fcgi://phpfpm-service:9000"
</FilesMatch>

ProxyFCGIBackendType GENERIC

Listen 443

<VirtualHost *:443>
    ServerName localhost

    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/custom_conf/server.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/custom_conf/server.key"

    <Directory "/var/www/html"> 
      AllowOverride All
      Require all granted
    </Directory>

    <FilesMatch \.php$>
	  SetHandler "proxy:fcgi://phpfpm-service:9000"
    </FilesMatch>

    ProxyFCGIBackendType GENERIC

</VirtualHost>    





