LoadModule rewrite_module modules/mod_rewrite.so

DocumentRoot "/var/www/html"
DirectoryIndex index.php index.html

# ==========================================
# GLOBAL CONTEXT (Port 80 HTTP / Liveness Probe)
# ==========================================
<Directory "/var/www/html">
    AllowOverride All
    Require all granted
</Directory>

<FilesMatch \.php$>
    SetHandler "proxy:fcgi://phpfpm-service:9000"
</FilesMatch>

ProxyFCGIBackendType GENERIC

Listen 443

# ==========================================
# SSL VIRTUAL HOST CONTEXT (Port 443 HTTPS / User Traffic)
# ==========================================
<VirtualHost *:443>
    ServerName localhost

    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/custom_conf/server.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/custom_conf/server.key"

    <Directory "/var/www/html">
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://phpfpm-service:9000"
    </FilesMatch>

    ProxyFCGIBackendType GENERIC
</VirtualHost>
