apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bookcatalogapp
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ==
  DB_NAME: Ym9va2FwcGRi
  DB_USER: Ym9va2FwcF9hZG1pbg==
  DB_PASS: ZXhhbXBsZQ==
